# Misc global config stuff

# World Y levels
top-y: 319
ocean-level: 62
deepslate-top: 2     # Y level where deepslate begins to replace stone
deepslate-bottom: -4 # Y level where all stone is replaced by deepslate
bedrock-top: -59     # Y level where deepslate starts to be replaced by bedrock
bottom-y: -64

palette-bottom: # Added to the bottom of every biome palette stack
  - DEEPSLATE: $meta.yml:deepslate-top
  - BEDROCK: $meta.yml:bedrock-top
  - BLOCK:minecraft:bedrock: $meta.yml:bottom-y
  
palette-bedrock: # Added to the bottom of every biome palette stack that uses its own deepslate palette
  - BEDROCK: $meta.yml:bedrock-top
  - BLOCK:minecraft:bedrock: $meta.yml:bottom-y
  