name: Upload to Archive.org
on: push

jobs:
  job:
    name: Upload
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install internetarchive

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
            fetch-depth: 0
            
      - name: Create bundle
        run: git bundle create origenCortexAnarchy-${{ github.sha }}.bundle --all

      - name: Upload file to archive.org
        run: |
          ia configure -u ${{ secrets.IA_USER }} -p ${{ secrets.IA_PWD }}
          ia upload origenCortexAnarchy-${{ github.sha }} origenCortexAnarchy-${{ github.sha }}.bundle --metadata="mediatype:software" --metadata="creator:Octagon Development" --metadata="title:origenCortexAnarchy-${{ github.sha }}" --metadata="scanner:Origen CortexAnarchy Auto-Archive" --metadata="collection:open_source_software" --metadata="subject:origen;cortex;cortexnodes;anarchy;minecraft;terra;github;cortexanarchy;octagon development" --metadata="originalurl:https://github.com/Octagon-Modding/Origen-CortexAnarchy" --retries 20